apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  ports:
    - port: 8086
      name: influxdb
      targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP