apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-data-sync
  namespace: data-sync
spec:
  selector:
    matchLabels:
      app: ms-data-sync
  replicas: 1 # To be updated
  template:
    metadata:
      labels:
        app: ms-data-sync
    spec:
      containers:
        - name: ms-data-sync
          image: udite/ms-data-sync:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka.kafka.svc.cluster.local:9092
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-sync-secrets
                  key: postgres_password
            - name: POSTGRES_HOST
              value: postgres.data-sync.svc.cluster.local:5432