apiVersion: v1
kind: Secret
metadata:
  name: data-sync-secrets
  namespace: data-sync
data:
  postgres_password: cGFzc3dvcmQ= # to change from password
  influx_db: cGFzc3dvcmQ= # to change from password