apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: spark-local
  hostPath:
    path: /mnt/spark-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: data-lake
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: spark-local
  resources:
    requests:
      storage: 1Gi
