apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-event-classifier
  namespace: event-classifier
spec:
  selector:
    matchLabels:
      app: ms-event-classifier
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-event-classifier
    spec:
      containers:
        - name: ms-event-classifier
          image: udite/ms-event-classifier:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: SIMULATOR_URL
              value: ms-simulator.simulator.svc.cluster.local:8000
            - name: KAFKA_BOOTSTRAP
              value: kafka.kafka.svc.cluster.local:9092
            - name: REDIS_HOST
              value: redis.event-classifier.svc.cluster.local:6379