apiVersion: v1
kind: PersistentVolume
metadata:
  name: event-classifer-volume
  namespace: event-classifier
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/model"
